import type { ServiceData } from './types';

export const SERVICES: ServiceData[] = [
  {
    id: 'excursions',
    title: 'Excursions & Aventures',
    subtitle: 'Désert, montagne, grand air',
    img: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1600&q=85',
    thumb: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600&q=80',
    price: 'À partir de 250 MAD / pers.',
    priceNum: 250,
    rating: '4.9',
    reviews: '127 avis',
    cat: 'Aventure',
    desc: "Partez à la découverte des paysages époustouflants qui entourent Marrakech. Du désert d'Agafay aux dunes du Sahara, en passant par les sommets de l'Atlas et les gorges du Dadès, nos excursions sont conçues pour vous offrir des souvenirs inoubliables. Chaque aventure est organisée par nos guides locaux certifiés, passionnés par leur région.",
    tags: ['Désert', 'Montagne', 'Aventure', 'Marrakech', 'Excursion', 'Nature'],
    included: [
      ['Transport aller-retour', 'Véhicule 4x4 climatisé depuis votre hébergement'],
      ['Guide professionnel', 'Guide francophone ou anglophone selon votre choix'],
      ['Déjeuner berbère', 'Repas traditionnel inclus pour les excursions à la journée'],
      ['Équipement', 'Tout le matériel nécessaire fourni'],
    ],
    info: [
      ['Durée', 'Demi-journée (4h) ou journée complète (10h)'],
      ['Départ', 'Depuis votre hébergement à Marrakech'],
      ['Groupe', 'Maximum 8 personnes par guide'],
      ['Langue', 'Français, Anglais, Arabe, Espagnol'],
    ],
    options: ['Demi-journée Agafay', 'Journée Atlas & Vallées', '2 jours Sahara Merzouga', 'Montgolfière lever du soleil', 'Quad & Buggy désert'],
    extras: [
      ['Nuit en bivouac Sahara', '+ 800 MAD / pers.'],
      ['Photographe pro', '+ 500 MAD'],
      ['Transfert privé VIP', '+ 300 MAD'],
    ],
    reviewsList: [
      { a: 'Sophie M.', d: 'Janvier 2025', s: 5, t: "Excursion au désert d'Agafay absolument magique. Le guide était formidable et le déjeuner berbère délicieux !" },
      { a: 'Thomas D.', d: 'Février 2025', s: 5, t: 'Superbe journée dans l\'Atlas. Organisation parfaite, paysages à couper le souffle.' },
    ],
  },
  {
    id: 'bienetre',
    title: 'Bien-Être & Détente',
    subtitle: 'Hammam, spa & rituels marocains',
    img: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1600&q=85',
    thumb: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80',
    price: 'À partir de 200 MAD / pers.',
    priceNum: 200,
    rating: '4.8',
    reviews: '98 avis',
    cat: 'Bien-Être',
    desc: "Plongez dans les traditions ancestrales du bien-être marocain. Nos partenaires spas et hammams offrent des soins d'exception dans des écrins de beauté authentiques. Du hammam traditionnel au massage aux huiles d'argan, chaque soin est une parenthèse hors du temps.",
    tags: ['Hammam', 'Spa', 'Massage', 'Bien-être', 'Relaxation', 'Rituels'],
    included: [
      ['Hammam traditionnel', 'Gommage au savon beldi et kessa inclus'],
      ['Huile d\'argan', 'Soins 100% naturels marocains'],
      ['Serviettes & peignoir', 'Fournis sur place'],
      ['Boisson de bienvenue', 'Thé à la menthe ou eau infusée'],
    ],
    info: [
      ['Durée', '1h30 à 3h selon la formule'],
      ['Lieu', 'Riad ou spa partenaire à Marrakech'],
      ['Réservation', '48h à l\'avance recommandée'],
      ['Langue', 'Français, Anglais'],
    ],
    options: ['Hammam classique', 'Ritual argan complet', 'Massage aux pierres chaudes', 'Cours de yoga privé', 'Journée spa VIP'],
    extras: [
      ['Extension massage 30min', '+ 180 MAD'],
      ['Soins visage', '+ 250 MAD'],
      ['Transfert inclus', '+ 120 MAD'],
    ],
    reviewsList: [
      { a: 'Amélie R.', d: 'Mars 2025', s: 5, t: 'Le hammam était une expérience extraordinaire. Tout était parfait, le cadre, les soins et l\'accueil.' },
      { a: 'Marc L.', d: 'Décembre 2024', s: 5, t: 'Massage aux huiles d\'argan incroyable. Je recommande vivement le ritual complet.' },
    ],
  },
  {
    id: 'transport',
    title: 'Transport & Transferts',
    subtitle: 'Aéroport, chauffeur privé & location',
    img: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=1600&q=85',
    thumb: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&q=80',
    price: 'À partir de 150 MAD / trajet',
    priceNum: 150,
    rating: '4.9',
    reviews: '203 avis',
    cat: 'Transport',
    desc: 'Voyagez sereinement avec nos services de transport premium. Transferts aéroport, chauffeur privé disponible 24h/24, ou location de véhicule avec ou sans chauffeur. Tous nos chauffeurs sont formés, assurés et parlent français.',
    tags: ['Transport', 'Aéroport', 'Chauffeur', 'Transfert', 'Location', 'VIP'],
    included: [
      ['Chauffeur professionnel', 'Formé, assuré, ponctuel'],
      ['Véhicule climatisé', 'Berline ou SUV selon votre besoin'],
      ['Eau & WiFi', 'À bord pour votre confort'],
      ['Suivi de vol', 'Adaptation en temps réel pour les transferts aéroport'],
    ],
    info: [
      ['Disponibilité', '24h/24, 7j/7'],
      ['Réservation', '2h minimum à l\'avance'],
      ['Flotte', 'Mercedes, BMW, Toyota Land Cruiser'],
      ['Zone', 'Marrakech & région (Agadir, Casablanca sur demande)'],
    ],
    options: ['Transfert aéroport aller simple', 'Transfert aller-retour', 'Chauffeur à la journée', 'Location voiture (avec chauffeur)', 'Service VIP conciergerie'],
    extras: [
      ['Accueil avec pancarte', '+ 50 MAD'],
      ['Siège enfant', 'Gratuit sur demande'],
      ['Second arrêt', '+ 80 MAD'],
    ],
    reviewsList: [
      { a: 'Jean-Pierre B.', d: 'Février 2025', s: 5, t: 'Chauffeur ponctuel, voiture impeccable. Le meilleur transfert que j\'ai eu à Marrakech.' },
      { a: 'Claire V.', d: 'Janvier 2025', s: 5, t: 'Service 5 étoiles. Le chauffeur nous attendait à l\'arrivée et a même porté nos bagages.' },
    ],
  },
  {
    id: 'gastro',
    title: 'Expériences Gastronomiques',
    subtitle: 'Chef privé, cours cuisine & dîners',
    img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1600&q=85',
    thumb: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
    price: 'À partir de 300 MAD / pers.',
    priceNum: 300,
    rating: '4.9',
    reviews: '76 avis',
    cat: 'Gastronomie',
    desc: 'Découvrez la richesse de la cuisine marocaine avec nos chefs privés et nos expériences culinaires uniques. Cours de cuisine dans un riad traditionnel, dîner aux chandelles sur une terrasse de la médina, brunch en rooftop avec vue sur les toits de Marrakech.',
    tags: ['Gastronomie', 'Chef privé', 'Cuisine marocaine', 'Cours cuisine', 'Dîner', 'Rooftop'],
    included: [
      ['Chef certifié', 'Formé aux arts culinaires marocains et français'],
      ['Ingrédients frais', 'Produits du marché local, 100% frais'],
      ['Ustensiles', 'Tout le matériel fourni pour les cours'],
      ['Recettes', 'Livret de recettes offert'],
    ],
    info: [
      ['Durée', '2h (cours) à 3h (dîner complet)'],
      ['Lieu', 'Votre hébergement ou riad partenaire'],
      ['Groupe', 'Jusqu\'à 12 personnes'],
      ['Régimes', 'Végétarien, halal, sans gluten sur demande'],
    ],
    options: ['Cours tajine & couscous', 'Dîner privé marocain', 'Brunch rooftop', 'Cours pâtisserie orientale', 'Chef à domicile (soirée)'],
    extras: [
      ['Accord vins & cocktails sans alcool', '+ 200 MAD / pers.'],
      ['Décoration romantique', '+ 350 MAD'],
      ['Animation musicale', '+ 600 MAD'],
    ],
    reviewsList: [
      { a: 'Isabelle K.', d: 'Mars 2025', s: 5, t: 'Le cours de cuisine était absolument génial ! Le chef était passionné et les plats délicieux.' },
      { a: 'Antoine P.', d: 'Février 2025', s: 5, t: 'Dîner privé sur la terrasse, vue magique sur la médina. Une soirée inoubliable.' },
    ],
  },
  {
    id: 'activites',
    title: 'Activités & Loisirs',
    subtitle: 'Jardin Majorelle, soirées & shooting',
    img: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1600&q=85',
    thumb: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=600&q=80',
    price: 'À partir de 150 MAD / pers.',
    priceNum: 150,
    rating: '4.7',
    reviews: '145 avis',
    cat: 'Loisirs',
    desc: 'De la visite du célèbre Jardin Majorelle aux soirées privées dans les meilleurs clubs de Marrakech, en passant par les balades en calèche dans la médina, nous organisons toutes vos activités et loisirs sur mesure.',
    tags: ['Loisirs', 'Jardin Majorelle', 'Médina', 'Soirée', 'Activités', 'Culture'],
    included: [
      ['Entrées incluses', 'Billets pré-réservés sans file d\'attente'],
      ['Guide culturel', 'Pour les visites historiques'],
      ['Calèche privée', 'Pour les balades en médina'],
      ['Recommandations', 'Meilleures tables et spots locaux'],
    ],
    info: [
      ['Durée', '2h à 6h selon l\'activité'],
      ['Disponibilité', 'Toute l\'année, réservation 24h à l\'avance'],
      ['Groupe', 'De 1 à 20 personnes'],
      ['Personnalisation', 'Itinéraire 100% sur mesure'],
    ],
    options: ['Visite Jardin Majorelle + Musée YSL', 'Balade calèche médina', 'Soirée spectacle folklorique', 'Shooting photo Marrakech', 'Accès club privé'],
    extras: [
      ['Photographe professionnel', '+ 500 MAD / 2h'],
      ['Guide privé exclusif', '+ 300 MAD / demi-journée'],
    ],
    reviewsList: [
      { a: 'Laura M.', d: 'Avril 2025', s: 5, t: 'La visite du Jardin Majorelle sans file d\'attente, c\'est magique ! Merci Harmonia.' },
    ],
  },
  {
    id: 'domicile',
    title: 'Services à Domicile',
    subtitle: 'Ménage, livraison & baby-sitting',
    img: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1600&q=85',
    thumb: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
    price: 'Sur devis',
    priceNum: 0,
    rating: '4.8',
    reviews: '89 avis',
    cat: 'Domicile',
    desc: 'Profitez pleinement de votre séjour pendant que nous gérons votre quotidien. Ménage professionnel, courses et livraison à domicile, petit-déjeuner servi dans votre riad, baby-sitting certifié — nous assurons votre confort à tout moment.',
    tags: ['Ménage', 'Domicile', 'Baby-sitting', 'Livraison', 'Confort', 'Services'],
    included: [
      ['Produits professionnels', 'Produits ménagers fournis'],
      ['Personnel certifié', 'Équipe vérifiée et assurée'],
      ['Discrétion garantie', 'Respect total de votre vie privée'],
      ['Flexibilité', 'Intervention à l\'heure qui vous convient'],
    ],
    info: [
      ['Disponibilité', '7j/7, 8h-20h'],
      ['Délai', 'Service le jour même selon disponibilité'],
      ['Zone', 'Marrakech intra-muros et périphérie'],
      ['Tarifs', 'Devis sur mesure selon prestations'],
    ],
    options: ['Ménage complet', 'Petit-déjeuner servi', 'Baby-sitting à la soirée', 'Courses & livraison', 'Repassage & linge'],
    extras: [
      ['Service express', '+ 20% du tarif normal'],
      ['Week-end & jours fériés', '+ 30%'],
    ],
    reviewsList: [
      { a: 'Caroline F.', d: 'Mars 2025', s: 5, t: 'Service de baby-sitting impeccable. La nounou était formidable avec mes enfants.' },
    ],
  },
  {
    id: 'shopping',
    title: 'Shopping & Artisanat',
    subtitle: 'Guide, personal shopper & souvenirs',
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=85',
    thumb: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    price: 'Sur devis',
    priceNum: 0,
    rating: '4.7',
    reviews: '67 avis',
    cat: 'Shopping',
    desc: 'Explorez les souks de Marrakech avec un guide local expert. Évitez les pièges touristiques, découvrez les meilleurs artisans, négociez aux meilleurs prix. Notre service Personal Shopper vous accompagne pour des achats authentiques et personnalisés.',
    tags: ['Shopping', 'Souks', 'Artisanat', 'Personal Shopper', 'Médina', 'Marrakech'],
    included: [
      ['Guide shopping local', 'Expert des souks et artisans'],
      ['Conseils authenticité', 'Garantir l\'origine des produits'],
      ['Aide à la négociation', 'Obtenez les vrais prix locaux'],
      ['Livraison à l\'hôtel', 'Vos achats livrés à votre hébergement'],
    ],
    info: [
      ['Durée', '2h à 4h'],
      ['Lieu', 'Souks de la médina de Marrakech'],
      ['Groupe', 'Maximum 6 personnes'],
      ['Langue', 'Français, Arabe, Anglais'],
    ],
    options: ['Tour souks + guide', 'Personal Shopper demi-journée', 'Atelier poterie ou zellige', 'Livraison souvenirs à domicile'],
    extras: [
      ['Transport des achats', '+ 150 MAD'],
      ['Emballage cadeau', '+ 80 MAD'],
    ],
    reviewsList: [
      { a: 'Nadia B.', d: 'Février 2025', s: 5, t: 'Le guide nous a emmenés dans des endroits incroyables, loin des zones touristiques. J\'ai ramené de magnifiques tapis.' },
    ],
  },
  {
    id: 'evenements',
    title: 'Événements & Célébrations',
    subtitle: 'Anniversaires, EVJF, mariages & demandes en mariage',
    img: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=1600&q=85',
    thumb: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&q=80',
    price: 'Sur devis',
    priceNum: 0,
    rating: '5.0',
    reviews: '54 avis',
    cat: 'Événements',
    desc: 'Créez des souvenirs inoubliables à Marrakech. Nos équipes prennent en charge l\'organisation complète de vos événements : EVJF, EVG, anniversaires, demandes en mariage, dîners romantiques ou soirées privées. Chaque détail est soigné pour que votre événement soit unique.',
    tags: ['Événements', 'Mariage', 'EVJF', 'Anniversaire', 'Romantique', 'Célébration'],
    included: [
      ['Coordination complète', 'Un chef de projet dédié à votre événement'],
      ['Décoration sur mesure', 'Thème et décoration selon vos souhaits'],
      ['Traiteur partenaire', 'Cuisine marocaine ou internationale'],
      ['Coordination le jour J', 'Notre équipe présente pour tout gérer'],
    ],
    info: [
      ['Préavis', '1 semaine minimum, idéalement 1 mois'],
      ['Capacité', 'De 2 à 200 personnes'],
      ['Lieu', 'Riad, palais, terrasse, jardin, désert'],
      ['Personnalisation', '100% sur mesure'],
    ],
    options: ['EVJF / EVG complet', 'Demande en mariage orchestrée', 'Anniversaire privatisé', 'Dîner romantique', 'Soirée privée (DJ, animation)'],
    extras: [
      ['Photographe & vidéaste', '+ 1 500 MAD'],
      ['Feux d\'artifice', '+ 2 500 MAD'],
      ['Animation musicale live', '+ 3 000 MAD'],
    ],
    reviewsList: [
      { a: 'Emma & Lucas', d: 'Mars 2025', s: 5, t: 'Harmonia a organisé notre demande en mariage au désert. C\'était féerique, on ne pouvait rêver mieux !' },
      { a: 'Sarah T.', d: 'Janvier 2025', s: 5, t: 'EVJF parfaitement organisé. Le groupe a adoré chaque moment. Merci infiniment !' },
    ],
  },
  {
    id: 'packs',
    title: 'Packs Sur-Mesure',
    subtitle: 'Séjours clés en main, 100% personnalisés',
    img: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1600&q=85',
    thumb: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
    price: 'Nous consulter',
    priceNum: 0,
    rating: '5.0',
    reviews: '38 avis',
    cat: 'Sur-Mesure',
    desc: 'Pour ceux qui veulent vivre Marrakech sans s\'occuper d\'aucun détail. Nos packs sur-mesure incluent l\'hébergement, les transferts, les activités, les repas et la conciergerie complète. Dites-nous vos envies, nous construisons votre séjour idéal.',
    tags: ['Pack', 'Sur-mesure', 'Séjour', 'Luxe', 'Tout inclus', 'Conciergerie'],
    included: [
      ['Hébergement sélectionné', 'Riad ou villa selon votre budget'],
      ['Tous les transferts', 'Aéroport et déplacements inclus'],
      ['Activités personnalisées', 'Programme adapté à vos souhaits'],
      ['Conciergerie dédiée', 'Un conseiller disponible 24h/24'],
    ],
    info: [
      ['Durée', '2 nuits minimum'],
      ['Budget', 'À partir de 5 000 MAD / personne'],
      ['Délai', '1 semaine à l\'avance'],
      ['Flexibilité', 'Programme modifiable à tout moment'],
    ],
    options: ['Weekend romantique (2 nuits)', 'Séjour famille (5 nuits)', 'Pack aventure solo', 'Voyage de groupe'],
    extras: [
      ['Extension Sahara', 'Sur devis'],
      ['Extension côte atlantique', 'Sur devis'],
    ],
    reviewsList: [
      { a: 'François & Marie', d: 'Avril 2025', s: 5, t: 'Un séjour absolument parfait de A à Z. Harmonia a pensé à tout, on n\'a eu qu\'à profiter.' },
    ],
  },
  {
    id: 'cadeaux',
    title: 'Produits & Cadeaux',
    subtitle: 'Huile d\'argan, coffrets & produits du terroir',
    img: 'https://images.unsplash.com/photo-1611006174913-c8d9e5d5b1a2?w=1600&q=85',
    thumb: 'https://images.unsplash.com/photo-1611006174913-c8d9e5d5b1a2?w=600&q=80',
    price: 'À partir de 120 MAD',
    priceNum: 120,
    rating: '4.8',
    reviews: '112 avis',
    cat: 'Cadeaux',
    desc: 'Rapportez un peu du Maroc avec vous ou offrez un coffret authentique à vos proches. Huile d\'argan pure, produits cosmétiques naturels, épices sélectionnées, coffrets cadeaux et produits du terroir — tout est sourcé directement auprès des producteurs locaux et livrable à domicile.',
    tags: ['Argan', 'Cosmétiques', 'Terroir', 'Cadeaux', 'Artisanal', 'Naturel'],
    included: [
      ['Produits certifiés', '100% naturels et authentiques marocains'],
      ['Emballage cadeau', 'Présentation soignée incluse'],
      ['Livraison à l\'hôtel', 'Livraison gratuite à votre hébergement à Marrakech'],
      ['Carte personnalisée', 'Message personnalisé offert'],
    ],
    info: [
      ['Livraison Marrakech', 'Sous 24h'],
      ['Livraison internationale', 'Sous 5-7 jours ouvrés'],
      ['Retours', 'Satisfait ou remboursé 15 jours'],
      ['Paiement', 'CB, virement, espèces'],
    ],
    options: ['Coffret argan complet', 'Set épices premium', 'Cosmétiques naturels', 'Coffret découverte Maroc', 'Pack souvenir artisanal'],
    extras: [
      ['Gravure personnalisée', '+ 60 MAD'],
      ['Livraison express', '+ 100 MAD'],
    ],
    reviewsList: [
      { a: 'Martine G.', d: 'Mars 2025', s: 5, t: 'Le coffret argan était magnifique, mes amies ont adoré. Produits de qualité exceptionnelle.' },
      { a: 'David R.', d: 'Février 2025', s: 4, t: 'Produits authentiques, bien emballés. Livraison rapide à mon hôtel.' },
    ],
  },
];

export const SERVICE_MAP = Object.fromEntries(SERVICES.map((s) => [s.id, s]));
